#!/bin/bash
rm -rf /etc/yum.repos.d/*
curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
yum -y groups install "GNOME Desktop"
### 修改配置文件
### vi /etc/gdm/custom.conf

### 增加如下配置
### [daemon]
### AutomaticLoginEnable=True
### AutomaticLogin=root

sed -i 's/daemon]/daemon] \
AutomaticLoginEnable=True \
AutomaticLogin=root /' /etc/gdm/custom.conf


wget -O /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo
yum install -y xrdp
yum install -y tigervnc-server
systemctl start xrdp
systemctl enable xrdp
systemctl stop firewalld
systemctl disable firewalld
