#!/bin/bash
read -p "请设定默认的域:" yu
read -p "请设定默认帐号的密码:" pass
a=`ip a | grep global | sed 's/inet//g' | sed 's#'/'.*##' | sed 's/ //g'`

###关闭selinux
setenforce 0
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux

###安装yum-utils工具
#yum update -y 
yum install -y yum-utils

###添加docker-ce源
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
###安装docker
yum install docker-ce -y

###启动docker
systemctl start docker
systemctl enable docker

###关闭防火墙
systemctl stop firewalld 
systemctl mask firewalld
systemctl disable firewalld



###安装并启动openldap
systemctl start docker
docker pull osixia/openldap
docker run -p 389:389 --name openldap --restart=always --env LDAP_ORGANISATION="$yu" --env LDAP_DOMAIN="$yu.com" --env LDAP_ADMIN_PASSWORD="$pass" --detach osixia/openldap

###重启docker和openldap
systemctl restart docker
docker restart openldap


###查询刚刚建立的openldap的内网ip
noip=`docker inspect openldap | grep 'IPAddress":' | sed -n '1p' | sed 's/"//g' | sed 's/.*://' | sed 's/,//' | sed 's/ //g'`


###安装并启动phpldapadmin
docker pull osixia/phpldapadmin

docker run -d --privileged -p 10004:80 --name myphpldapadmin --env PHPLDAPADMIN_HTTPS=false --env PHPLDAPADMIN_LDAP_HOSTS="$noip" --detach osixia/phpldapadmin



###因为我们使用的是docker的yum源，所以要重启下，
###因为docker服务启动时定义的自定义链DOCKER由于某种原因被清掉
###只要重启下就可以还原自定义链DOCKER
docker restart myphpldapadmin



docker ps


echo "登陆dn：cn=admin,dc=$yu,dc=com"
echo "登陆dn密码：$pass"
echo "登陆网址：http://$a:10004"
